//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.5.1
//     from Assets/InputsActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputsActions: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputsActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputsActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""14bb221c-fc2c-453c-a021-ba41a8af4998"",
            ""actions"": [
                {
                    ""name"": ""ZoomValue"",
                    ""type"": ""Value"",
                    ""id"": ""83aed690-5381-4292-b67a-ca86e34ffb3a"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClickButton"",
                    ""type"": ""Button"",
                    ""id"": ""8e6dfc17-5552-4d1a-91e1-c00b293162d2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DoubleClickButton"",
                    ""type"": ""Button"",
                    ""id"": ""a0c3497e-bd7a-4c9a-b2bb-3a1a63f52f0a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TripleClickButton"",
                    ""type"": ""Button"",
                    ""id"": ""71d0baa8-5fcd-4990-b973-44ae6895d669"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": ""MultiTap(tapCount=3)"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LongPressButton"",
                    ""type"": ""Button"",
                    ""id"": ""66145a7b-3fa2-4b91-9e79-b4a907eec7d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PointerPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""2dd3d8d3-9e5a-4b4c-9c31-d0c700a5134e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Drag"",
                    ""type"": ""Button"",
                    ""id"": ""343aba71-8628-47cc-9091-9a9b6b9c2006"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""DragBuildMode"",
                    ""type"": ""Button"",
                    ""id"": ""f51fbea9-9c0d-4f48-8771-fa82bf328674"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ClickBuildMode"",
                    ""type"": ""Button"",
                    ""id"": ""d77b3c51-a9a6-44ee-97c4-a11cd2304021"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""ca2c8752-ee04-487c-9175-4a90ce7891d2"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""ZoomValue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""Pinch"",
                    ""id"": ""16992aac-a28d-4c53-8e6e-c80903a91968"",
                    ""path"": ""Pinch"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ZoomValue"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""m_FirstFingerPositionValueId"",
                    ""id"": ""c4960551-ab97-43c2-87b8-45ce1a2831e4"",
                    ""path"": ""<Touchscreen>/touch0/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""ZoomValue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""m_SecondFingerPositionValueId"",
                    ""id"": ""5179b7f8-d51a-4153-a650-22a2720d3522"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""ZoomValue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""cdd605dd-e4d8-4a36-8748-85c07065dc77"",
                    ""path"": ""<Touchscreen>/touch0/tap"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""ClickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9f0fd21f-3910-48e7-8dde-cdb18b4443be"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""ClickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""14f6a610-98a3-4c82-89b2-bf8968f18374"",
                    ""path"": ""<Touchscreen>/touch0/press"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""LongPressButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""52b7bb6f-3a48-4991-b51d-c4d1185d0784"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""LongPressButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e269523-5df9-4ab6-a2da-8b7738d1f8c7"",
                    ""path"": ""<Touchscreen>/touch0/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""DoubleClickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cdb8f697-2d3a-48e6-9027-a67084435114"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""DoubleClickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8a5110a-e146-47b5-82cc-44641903de12"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""PointerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8f4e9f8a-a647-427f-b6ec-5fe5896262c5"",
                    ""path"": ""<Touchscreen>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""PointerPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dc60821b-0759-4c64-a680-1177b9ef283c"",
                    ""path"": ""<Touchscreen>/touch0/tap"",
                    ""interactions"": ""Tap"",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""ClickBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8ad2ef7-262b-4acc-96be-c37636fa90a2"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""ClickBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""613c4e9c-fad5-4d23-9bcf-b477f38577e1"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""TripleClickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f76554e1-9e03-478d-aa70-dd7e14648404"",
                    ""path"": ""<Touchscreen>/touch0/tap"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""TripleClickButton"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d24390b2-dc7e-4a58-98a0-662eecca9cd5"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dbc9047d-0341-4e53-bbe3-2e42aa000f31"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""Drag"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8d3463ee-0fec-4687-9b95-633f13d8e2d7"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""KBM"",
                    ""action"": ""DragBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1b216fa3-48dc-478a-950f-4403920f6f47"",
                    ""path"": ""<Touchscreen>/Press"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": ""Touchscreen"",
                    ""action"": ""DragBuildMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""KBM"",
            ""bindingGroup"": ""KBM"",
            ""devices"": [
                {
                    ""devicePath"": ""<Keyboard>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<Mouse>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        },
        {
            ""name"": ""Touchscreen"",
            ""bindingGroup"": ""Touchscreen"",
            ""devices"": [
                {
                    ""devicePath"": ""<Touchscreen>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_ZoomValue = m_Player.FindAction("ZoomValue", throwIfNotFound: true);
        m_Player_ClickButton = m_Player.FindAction("ClickButton", throwIfNotFound: true);
        m_Player_DoubleClickButton = m_Player.FindAction("DoubleClickButton", throwIfNotFound: true);
        m_Player_TripleClickButton = m_Player.FindAction("TripleClickButton", throwIfNotFound: true);
        m_Player_LongPressButton = m_Player.FindAction("LongPressButton", throwIfNotFound: true);
        m_Player_PointerPosition = m_Player.FindAction("PointerPosition", throwIfNotFound: true);
        m_Player_Drag = m_Player.FindAction("Drag", throwIfNotFound: true);
        m_Player_DragBuildMode = m_Player.FindAction("DragBuildMode", throwIfNotFound: true);
        m_Player_ClickBuildMode = m_Player.FindAction("ClickBuildMode", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_ZoomValue;
    private readonly InputAction m_Player_ClickButton;
    private readonly InputAction m_Player_DoubleClickButton;
    private readonly InputAction m_Player_TripleClickButton;
    private readonly InputAction m_Player_LongPressButton;
    private readonly InputAction m_Player_PointerPosition;
    private readonly InputAction m_Player_Drag;
    private readonly InputAction m_Player_DragBuildMode;
    private readonly InputAction m_Player_ClickBuildMode;
    public struct PlayerActions
    {
        private @InputsActions m_Wrapper;
        public PlayerActions(@InputsActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @ZoomValue => m_Wrapper.m_Player_ZoomValue;
        public InputAction @ClickButton => m_Wrapper.m_Player_ClickButton;
        public InputAction @DoubleClickButton => m_Wrapper.m_Player_DoubleClickButton;
        public InputAction @TripleClickButton => m_Wrapper.m_Player_TripleClickButton;
        public InputAction @LongPressButton => m_Wrapper.m_Player_LongPressButton;
        public InputAction @PointerPosition => m_Wrapper.m_Player_PointerPosition;
        public InputAction @Drag => m_Wrapper.m_Player_Drag;
        public InputAction @DragBuildMode => m_Wrapper.m_Player_DragBuildMode;
        public InputAction @ClickBuildMode => m_Wrapper.m_Player_ClickBuildMode;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @ZoomValue.started += instance.OnZoomValue;
            @ZoomValue.performed += instance.OnZoomValue;
            @ZoomValue.canceled += instance.OnZoomValue;
            @ClickButton.started += instance.OnClickButton;
            @ClickButton.performed += instance.OnClickButton;
            @ClickButton.canceled += instance.OnClickButton;
            @DoubleClickButton.started += instance.OnDoubleClickButton;
            @DoubleClickButton.performed += instance.OnDoubleClickButton;
            @DoubleClickButton.canceled += instance.OnDoubleClickButton;
            @TripleClickButton.started += instance.OnTripleClickButton;
            @TripleClickButton.performed += instance.OnTripleClickButton;
            @TripleClickButton.canceled += instance.OnTripleClickButton;
            @LongPressButton.started += instance.OnLongPressButton;
            @LongPressButton.performed += instance.OnLongPressButton;
            @LongPressButton.canceled += instance.OnLongPressButton;
            @PointerPosition.started += instance.OnPointerPosition;
            @PointerPosition.performed += instance.OnPointerPosition;
            @PointerPosition.canceled += instance.OnPointerPosition;
            @Drag.started += instance.OnDrag;
            @Drag.performed += instance.OnDrag;
            @Drag.canceled += instance.OnDrag;
            @DragBuildMode.started += instance.OnDragBuildMode;
            @DragBuildMode.performed += instance.OnDragBuildMode;
            @DragBuildMode.canceled += instance.OnDragBuildMode;
            @ClickBuildMode.started += instance.OnClickBuildMode;
            @ClickBuildMode.performed += instance.OnClickBuildMode;
            @ClickBuildMode.canceled += instance.OnClickBuildMode;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @ZoomValue.started -= instance.OnZoomValue;
            @ZoomValue.performed -= instance.OnZoomValue;
            @ZoomValue.canceled -= instance.OnZoomValue;
            @ClickButton.started -= instance.OnClickButton;
            @ClickButton.performed -= instance.OnClickButton;
            @ClickButton.canceled -= instance.OnClickButton;
            @DoubleClickButton.started -= instance.OnDoubleClickButton;
            @DoubleClickButton.performed -= instance.OnDoubleClickButton;
            @DoubleClickButton.canceled -= instance.OnDoubleClickButton;
            @TripleClickButton.started -= instance.OnTripleClickButton;
            @TripleClickButton.performed -= instance.OnTripleClickButton;
            @TripleClickButton.canceled -= instance.OnTripleClickButton;
            @LongPressButton.started -= instance.OnLongPressButton;
            @LongPressButton.performed -= instance.OnLongPressButton;
            @LongPressButton.canceled -= instance.OnLongPressButton;
            @PointerPosition.started -= instance.OnPointerPosition;
            @PointerPosition.performed -= instance.OnPointerPosition;
            @PointerPosition.canceled -= instance.OnPointerPosition;
            @Drag.started -= instance.OnDrag;
            @Drag.performed -= instance.OnDrag;
            @Drag.canceled -= instance.OnDrag;
            @DragBuildMode.started -= instance.OnDragBuildMode;
            @DragBuildMode.performed -= instance.OnDragBuildMode;
            @DragBuildMode.canceled -= instance.OnDragBuildMode;
            @ClickBuildMode.started -= instance.OnClickBuildMode;
            @ClickBuildMode.performed -= instance.OnClickBuildMode;
            @ClickBuildMode.canceled -= instance.OnClickBuildMode;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    private int m_KBMSchemeIndex = -1;
    public InputControlScheme KBMScheme
    {
        get
        {
            if (m_KBMSchemeIndex == -1) m_KBMSchemeIndex = asset.FindControlSchemeIndex("KBM");
            return asset.controlSchemes[m_KBMSchemeIndex];
        }
    }
    private int m_TouchscreenSchemeIndex = -1;
    public InputControlScheme TouchscreenScheme
    {
        get
        {
            if (m_TouchscreenSchemeIndex == -1) m_TouchscreenSchemeIndex = asset.FindControlSchemeIndex("Touchscreen");
            return asset.controlSchemes[m_TouchscreenSchemeIndex];
        }
    }
    public interface IPlayerActions
    {
        void OnZoomValue(InputAction.CallbackContext context);
        void OnClickButton(InputAction.CallbackContext context);
        void OnDoubleClickButton(InputAction.CallbackContext context);
        void OnTripleClickButton(InputAction.CallbackContext context);
        void OnLongPressButton(InputAction.CallbackContext context);
        void OnPointerPosition(InputAction.CallbackContext context);
        void OnDrag(InputAction.CallbackContext context);
        void OnDragBuildMode(InputAction.CallbackContext context);
        void OnClickBuildMode(InputAction.CallbackContext context);
    }
}
